-- AlterTable
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "adultCapacity" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "childCapacity" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "mapUrl" TEXT,
ADD COLUMN IF NOT EXISTS "customFields" JSONB DEFAULT '[]';

-- AlterTable
ALTER TABLE "EventRSVP" ADD COLUMN IF NOT EXISTS "supportAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "customResponses" JSONB DEFAULT '{}';
